Completed some input services
annamarieweber/cellularautomataframework pull request #2
Opened 2021-11-29 23:23 UTC by ujamshed

- [ ] Created a couple constructors
- [ ] First constructor takes a legend as a map and a vector containing the data you want in the Cellular Automata
- [ ] Second constructor takes only a legend as a map and creates the Cellular Automata data randomly
- [ ] Von Neumann neighborhood is implemented
- [ ] Rudimentary print function to view the data in the class
- [ ] Some testing and utilities have been added, as well as new folders for bin, and include

2021-12-08 02:14 UTC, kimjoyc commented
lgtm

2021-12-08 02:16 UTC, kimjoyc submitted a review, later dismissed

2021-12-08 07:13 UTC, annamarieweber requested changes

2021-12-08 07:13 UTC, annamarieweber commented on .vscode/settings.json
> +{
add this to the .gitignore we don't want this in the repo it is your vscode settings

2021-12-09 02:57 UTC, annamarieweber commented
I will fix this

2021-12-09 02:57 UTC, merged